### ISSUE TITLE
Minor comments in executive file location 

### ISSUE THREAD

**Issue by ZhenchenHong** [Battery-Intelligence-Lab/DTWpp#12]
Hi authors, I am reviewing the code from https://github.com/openjournals/joss-reviews/issues/6881#issue-2349216956. Could you please add the directory of `dtwc_main` to help the user to specify the location? To be specifically, in `https://battery-intelligence-lab.github.io/dtw-cpp/1_getting_started/direct_use.html`, you may add the `./dtw-cpp/bin` to direct people to the correct path. Thanks!

**Comment by ElektrikAkar** [comment]
Hi, thank you very much for your comment, I have added the folder in the instructions in commit 4e3b51ef5b6bce9ccbc6690cb755bfbb0350d548. Please let me know if any further clarification is needed.

**Comment by i64** [comment]
I agree with @ZhenchenHong. I think the authors can also fix location confusion in the "running" section.

**Comment by ElektrikAkar** [comment]
Hi, 

Thank you very much for both your comment! You are right that there was a lot of confusion in the installation section. Now, we have fully updated the installation documentation https://github.com/Battery-Intelligence-Lab/dtw-cpp/pull/20

- We changed order of the items. 
- Corrected folder names. 
- Navitaged users to `bin` folder by `cd ../bin` command after building the software inside `build` folder. 
- Expanded the explanations for each operating system instead of referring to each other. 
- Added an [example project](https://github.com/Battery-Intelligence-Lab/dtw-cpp/tree/main/examples/example_project) inside examples to import DTW-C++ as a library. 
- Also corrected some of the default path variables defined inside CMake; where we seperated the `root` path as the path of the main project and `dtwc_folder` as the location of our library for finding example data easily.

Hopefully now it looks much better: https://battery-intelligence-lab.github.io/dtw-cpp/1_getting_started/1_installation.html

Please let us know if there are any further changes we can make to improve the quality of the documentation.

**Comment by i64** [comment]
Hi @ElektrikAkar,

I checked the commit. LGTM!

**Comment by ElektrikAkar** [comment]
Hi, as both reviewers are happy with the current state, I am closing the issue. Many thanks for your efforts.
