### ISSUE TITLE
Third-party software installation guidelines

### ISSUE THREAD

**Issue by i64** [Battery-Intelligence-Lab/DTWpp#16]
Hi authors, I am reviewing the code from [openjournals/joss-reviews#6881](https://github.com/openjournals/joss-reviews/issues/6881#issue-2349216956).

The third-party software (e.g., CMake, OpenMP, Gurobi) installation guidelines are missing and could be integrated into the documentation.

**Comment by i64** [comment]
Another thing is, in the Linux section, it should be made clear which linux distribution it is. Then for example the installation comments could be such as 

```
sudo apt install build-essential
sudo apt install cmake libomp-dev
```

**Comment by ElektrikAkar** [comment]
Hi,

Thank you very much for your comment! We have fully updated the installation documentation https://github.com/Battery-Intelligence-Lab/dtw-cpp/pull/20.

- We integrated CMake installation into the bash commands.
- OpenMP is mostly included in GCC and MSVC installations; however, we included the necessary command for Apple Clang and added a note on installing the required OpenMP version for Ubuntu.
- For Gurobi, we linked to the [visual guidelines](https://battery-intelligence-lab.github.io/dtw-cpp/1_getting_started/1_installation.html#gurobi) provided by the company. However, since it is a somewhat lengthy process and an optional dependency, we chose not to copy and paste all the steps.
- Lastly, we integrated [CPMLicenses.cmake](https://github.com/cpm-cmake/CPMLicenses.cmake) to print the licenses of some dependencies included in the binary executable. 

Please let us know if any further clarification on the third-party software is needed.

**Comment by i64** [comment]
Hi @ElektrikAkar,

I checked the commit. LGTM!
